production_app:
  children:
    Bastion:
      hosts:
        bastion_prod1:
          ansible_user: ubuntu
          ansible_host: 103.150.84.129
          ansible_port: 12200
          ansible_ssh_private_key_file: "keys/key.pem"
    Bootstrap:
      hosts:
        bootstrap1:
          ansible_user: ubuntu
          ansible_host: 192.168.2.17
          ansible_ssh_private_key_file: "keys/key.pem"
    aziz-app_builder:
      hosts:
        aziz-app_builder1:
          ansible_host: 192.168.2.8
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "keys/key.pem"
