---
- hosts: aziz-app_builder
  roles:
  - nginx
  vars:
    workdir: "{{ lookup('env', 'workdir') or '/home/ubuntu/aziz-app-{{ long_env }}' }}"
    version: "{{ lookup('env', 'version') or ansible_date_time.epoch }}"

- hosts: Bootstrap
  roles:
  - kubernetes
  vars_files:
  - "inventories/{{ long_env }}/group_vars/aziz-app_builder/vars.yml"
  tags:
  - deploy
