---
app_name: "aziz-app"
app_project_name: "{{ app_name }}"
domain_name: "lab-kube.azizpunya.com"
env: "{{ long_env }}"
port: "80"
ssl: true
ssl_name: "tls-{{ app_name }}"
app_base_dir: "/home/ubuntu/{{ app_name }}-{{ long_env }}"
project_harbor: "lab-kube"

git_branch: "main"
app_repo: "https://github.com/abdulazizms/reactjs.git"
